config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root to: 'welcome#index'

  get '*path' => redirect('/')

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name , :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate => true
  attribute :nickname, :captcha => true

  def headers
     {
        :subject => "Contact Form",
        :to => "wondercrust122@gmail.com",
        :from => %("#{name}" <#{email}>)
      }
  end
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged 
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = "Connot send message"
      render 'new'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_model!, except: [:index, :show]

  # Index action to render all Posts
  def index
    @posts = Post.all.order('created_at desc').paginate(:page => params[:page], :per_page => 3)
  end

  # New action to create new posts
  def new
    @post = Post.new
  end

  # Create action to save all new posts into the database
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] =  "Post created succussfully"
      redirect_to @post
    else
      flash[:alert] = "Oops!Something went wrong"
      render :new
    end
  end

  # Show action to render a post after retrieving its id
  def show
  end

  # Edit action to retrieve  a post for editing
  def edit
  end

  # Update action to update a post with new information
  def update
    if @post.update_attributes(post_params)
      flash[:notice] = "Post updated successfully"
      redirect_to @post
    else
      flash[:alert] = "Oops! Something went wrong"
      render :edit
    end
  end

  # Destroy action for removing a post permanently from a database
  def destroy
    if @post.destroy
      flash[:notice] = "Post deleted successfully"
      redirect_to posts_path
    else
      flash[:alert] = "Oopps! Something went wrong"
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_model!, except: [:index, :show]
  # Index action to render all Projects
  def index
    @projects = Project.all.order('created_at desc')
  end

  # New action to create new projects
  def new
    @project = Project.new
  end

  #Create action to save new projects into the db
  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project successfully saved"
      redirect_to @project
    else
      flash[:alert] = "Ooops!Something went wrong"
      render 'new'
    end
  end

  # Show action to render a project after retireving its id
  def show
  end

  # Edit action to edit projects
  def edit
  end

  # Update action to update old projects with new projects
  def update
    if  @project.update(project_params)
      flash[:notice] = "Project successfully updated"
      redirect_to @project
    else
      render 'edit'
    end
  end

  # Destroy action to permanently remove a project from a database
  def destroy
    @project.destroy
  end

  private
  def project_params
    params.require(:project).permit(:title, :description, :link,:slug)
  end
  def find_project
    @project = Project.friendly.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # Index action to retrieve all posts
  def index
    @posts = Post.all.limit(3).order('created_at desc')
    @projects = Project.all.limit(3).order('created_at desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code,language)
      Pygments.highlight(code,lexer: language)
    end
  end
  def markdown(content)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = HTMLwithPygments.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id='page_title'>Say Hello!</h1>
<div class="skinny_wrapper wrapper_padding">
  <h1>Thank you for your message</h1>
  <p>
    I'll get back to you shortly
  </p>
</div>

app/views/contacts/new.html.erb
<h1 id='page_title'>Say Hello!</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= form_for @contact do |f| %>
  <%= f.label :name %> <br>
  <%= f.text_field :name %>

  <br>
  <br>

  <%= f.label :email %> <br>
  <%= f.email_field :email, required: true %>

  <br>
  <br>

  <%= f.label :message %> <br>
  <%= f.text_area :message, as: :text %>

  <br>
  <br>

  <div class="hidden">
    <%= f.label :nickname %> <br>
    <%= f.text_field :nickname, hint: "leave this field blank" %>
  </div>

  <%=f.submit 'Send message', class: "button" %>
  <% end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Curtis -Ruby on Rails Developer</title>
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header id='main_navigation' class='clearfix'>
      <%= link_to "Curti-s Kirimi", root_path, class: "name" %>

      <nav>
        <%= link_to "Articles", posts_path %>
        <%= link_to "Projects", projects_path %>
        <%= link_to "Contacts", new_contact_path %>
        <% if model_signed_in? %>
          <%= link_to "Logout", destroy_model_session_path, method: :delete %>
          <% end %>
      </nav>
    </header>
    <% if notice %>
    <p class="notice"><%= notice %></p>
    <% elsif alert %>
    <p class="alert"><%= alert %></p>
    <% end %>

<%= yield %>

  <footer id="main_footer">
    <p class="copyright">&copy; 2016 Curti-s Kirmi</p>
    <nav>
      <a href="#"><i class="fa fa-snapchat" aria-hidden="true"></i></a>
      <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
      <a href="#"><i class="fa fa-github" aria-hidden="true"></i></a>
    </nav>
  </footer>

</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
 *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
 *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables */
/*
var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = '//recap-blog-1.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
        <h2>
          <%= pluralize(@post.errors.count, "errors") %> prevented the post from
          saving.
        </h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
        </ul>
    </div>
    <% end %>

    <%= f.label :title %> <br>
    <%= f.text_field :title %>

    <br>
    <br>

    <%= f.label :content %> <br>
    <%= f.text_area :content %>

    <br>
    <br>

    <%= f.submit %>
    <% end %>

app/views/posts/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
  <h1>Edit Project</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Stuff I might write</h1>

      <div id="posts_wrapper" class="skinny_wrapper">
        <div class="posts">
          <% @posts.each do |post| %>
          <p class="date"><%= post.created_at.strftime('%A %b %d')%> %></p>
          <h2><a href="#"><%= link_to post.title, post %></a></h2>
          <hr>
          <% end %>
        </div>
      </div>

      <%= will_paginate @posts %>

app/views/posts/new.html.erb
<div class="skinny_wrapper wrapper_padding">
  <h1>New Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
      <header>
        <p class="date"><%= @post.created_at.strftime('%A %b %d')%></p>
        <h1><%= @post.title %></h1>
        <hr>
      </header>
      <div id="content">
        <%= markdown @post.content%>
      </div>

      <br>
      <br>
      <% if model_signed_in? %>
        <div id='admin_links'>
          <%= link_to "Edit", edit_post_path(@post) %>
          <%= link_to "Delete", post_path, method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
      <% end %>

      <%= render 'disqus' %>

      <hr>

      <div id="share_box">
        <p>Share The DO list</p>
        <a href="#"><i class='fa fa-twitter'></i></a>
        <a href="#"><i class='fa fa-google-plus'></i></a>
        <a href="#"><i class='fa fa-facebook'></i></a>
      </div>

      <hr>

    </div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
        <h2>
          <%= pluralize(@project.errors.count, "errors") %> prevented the post from
          saving.
        </h2>
        <ul>
          <% @project.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
        </ul>
    </div>
    <% end %>

    <%= f.label :title %> <br>
    <%= f.text_field :title %>

    <br>
    <br>

    <%= f.label :description %> <br>
    <%= f.text_area :description %>

    <br>
    <br>
    <%= f.label :link %> <br>
    <%= f.text_field :link %>

    <br>
    <br>

    <%= f.submit %>
    <% end %>

app/views/projects/index.html.erb
<h1 id="page_title">Stuff I might build</h1>

      <div id="posts_wrapper" class="skinny_wrapper">
        <div class="posts">
          <% @projects.each do |project| %>
          <p class="date"><%= project.created_at.strftime('%A %b %d')%></p>
          <h2><a href="#"><%= link_to project.title, project %></a></h2>
          <hr>
          <% end %>
        </div>
      </div>

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_padding">
  <h1>New Project</h1>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
      <header>
        <p class="date"><%= @project.created_at.strftime('%A %b %d')%></p>
        <h1><%= @project.title %></h1>
        <hr>
      </header>
      <div id="content">
        <%= markdown @project.description%>
        <div class="button_wrapper">
          <a href='<%= @project.link%>' class='project_button'
            target="_blank">Visit <%= @project.title %></a>
        </div>
        <br>
        <br>
        <% if model_signed_in? %>
          <div id='admin_links'>
            <%= link_to "Edit", edit_post_path(@post) %>
            <%= link_to "Delete", post_path, method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
        <% end %>

      </div>
    </div>

app/views/welcome/index.html.erb
<div class="wrapper clearfix">
      <div class="col_1 homepage_content about">
        <h2>About</h2>
        <hr>
        <p>
          I am a badass Ruby on Rails developer &amp; aspiiring
          software engineer living in Nairobi Kenya.
        </p>
        <p>
          By day I work as a developer and by night I brace
          myself with coding skills from <a href='#'>Mackenzie Child></a>
          who is a really resourceful Ruby on Rails developer and designer.
        </p>
        <p>
          You can find me snapping on Snapchat,fiddling with
          140 characters on Twitter or replenishing my repo
          with applications that I intend to develop in Github.
        </p>
      </div>
      <div class="col_2 homepage_content">
        <h2>Stuff I might write</h2>
        <hr>
        <% @posts.each do |post| %>
        <h3><%= link_to post.title, post %></h3>
        <p class='date'><%= post.created_at.strftime('%A %b %d') %></p>
        <% end %>
      </div>
      <div class="col_3 homepage_content">
        <h2>Stuff I might build</h2>
        <hr>
        <% @projects.each do |project| %>
        <h3><%= link_to project.title, project %></h3>
        <p class='date'><%= project.created_at.strftime('%A %b %d') %></p>
        <% end %>

      </div>
    </div>